import type { Metadata } from "next";
import { Inter, Source_Serif_4, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Magic } from "@/context/magic.provider";
import { Wagmi } from "@/context/wagmi.provider";
import { QueryProvider } from "@/context/query.provider";
import { ServiceWorkerRegistration } from "@/components/service-worker-registration";
import { WalletAutoConnect } from "@/components/wallet/WalletAutoConnect";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const sourceSerif = Source_Serif_4({
  variable: "--font-source-serif",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${sourceSerif.variable} ${geistMono.variable} antialiased`}
      >
        <Magic>
          <Wagmi>
            <QueryProvider>
              <WalletAutoConnect />
              <ServiceWorkerRegistration />
              {children}
            </QueryProvider>
          </Wagmi>
        </Magic>
      </body>
    </html>
  );
}
